package source

/*
	Commandline configuration struct.  This will be the internal state
	of the logger which will be loaded by the commandline arguments
*/
type Configuration struct {
	AllowedChars string // Allowed characters to be used in any sequence or random words.
	BufferSize   int    // Size of the channel/queue used by the generator.
	Dictionary   string // Specifies the dictionary path/file.
	MaxWordCount int    // Maximum number of words to be generated.
	MaxWordSize  int    // Maximum number of characters in the word size.
	MinWordSize  int    // Minimum number of characters in the word size.
	Mode         string // Defines the mode (sequence, random, dictionary).
	Pattern      string // Regular expression string used to filter words generated by the source feed.
}
