package source

import "asymmetric-effort/asymmetric-toolkit/src/common/utils"

const (
	FlagDictionary     = "dictionary"
	FlagDictionaryText = "Specify the path/filename of a given dictionary file.  This dictionary file will be " +
		"in the proprietary file format implemented by the toolkit."
	FlagDictionaryDefault = ""

	FlagMaxWordCount     = "maxwordcount"
	FlagMaxWordCountText = "Specify the maximum number of words to generate from the standard source generator " +
		"using either the sequential, random or dictionary generator."
	FlagMaxWordCountDefault = 0
	FlagMaxWordCountLow     = 1
	FlagMaxWordCountHigh    = 1000000000

	FlagPattern        = "pattern"
	FlagPatternText    = "Specify a regular expression pattern as a string."
	FlagPatternDefault = utils.RegExDotPlusMan

	FlagSource     = "source"
	FlagSourceText = "Specify the type of word source to be used for an attack (sequence, random or dictionary) " +
		"where each source will generate a series of 'word' strings used as specified in the tool documentation."

	FlagSourceSequence   = "sequence"
	FlagSourceRandom     = "random"
	FlagSourceDictionary = "dictionary"


	FlagWordsize     = "wordsize"
	FlagWordSizeText = "Specify the number of characters in a word generated by the Sequence or Random " +
		"source generators."
	FlagWordSizeDefault = 0
	FlagWordSizeLow     = 1
	FlagWordSizeHigh    = 1024
)