package cli

/*
	Standardized CLI flags.

		Intention: We should reuse flags for all tools in the toolkit and standardize their expected
				   behavior.  This block of constants aims to do just that.
*/

const (
	FlagConcurrency     = "concurrency"
	FlagConcurrencyText = "Specify the number of concurrent operations to perform in the attack."
	FlagDebug           = "debug"
	FlagDebugText       = "Enable debug (verbose) logging in the logger facilities."
	FlagDelay           = "delay"
	FlagDelayText       = "Specify the number of seconds to wait between attack operations."
	FlagDepth           = "depth"
	FlagDepthText       = "Specify the depth of the attack (e.g. number of iterations or layers into a target) " +
		"an attack will go until the tool stops.  For example, in the case of dnsenum this flag will indicate " +
		"the number of subdomain levels which will be enumerated by brute force."
	FlagDictionary     = "dictionary"
	FlagDictionaryText = "Specify the path/filename of a given dictionary file.  This dictionary file will be " +
		"in the proprietary file format implemented by the toolkit."
	FlagDomain     = "domain"
	FlagDomainText = "Specify a fully-qualified or partial domain name string."
	FlagForce      = "force"
	FlagForceText  = "Specify that any operation which would otherwise fail should proceed with force.  " +
		"This may mean files are overwritten or other actions are taken without warning.  Use caution " +
		"and read the documentation for each tool specifically."
	FlagHelp                = "help"
	FlagHelpText            = "Show this help documentation."
	FlagLogDestionation     = "logdestination"
	FlagLogDestionationText = "Specify the destination for log activity (e.g. stdout, file, syslog)"
	FlagLogFile             = "logfile"
	FlagLogFileText         = "Specify the path/filename of a log file where file is the destination."
	FlagLogLevel            = "loglevel"
	FlagLogLevelText        = "Specify the logging level (string)."
	FlagLogServer			= "Specify the FQDN and port for sending logs to a syslog server."
	//ToDo: add TLS options for syslog.
	FlagMaxWordCount     = "maxwordcount"
	FlagMaxWordCountText = "Specify the maximum number of words to generate from the standard source generator " +
		"using either the sequential, random or dictionary generator."
	FlagSource     = "source"
	FlagSourceText = "Specify the type of word source to be used for an attack (sequence, random or dictionary) " +
		"where each source will generate a series of 'word' strings used as specified in the tool documentation."
	FlagOutput             = "output"
	FlagOutputText         = "Specify the output path/filename for the report to be generated following tool termination."
	FlagPattern            = "pattern"
	FlagPatternText        = "Specify a regular expression pattern as a string."
	FlagDNSRecordTypes     = "dnsrecordtypes"
	FlagDNSRecordTypesText = "DNS Record types list."
	FlagTarget             = "target"
	FlagTargetText         = "Specify an attack target (string)"
	FlagTimeout            = "timeout"
	FlagTimeoutText        = "Specify a connection timeout in (integer) seconds."
	FlagVersion            = "version"
	FlagVersionText        = "Show the toolkit/application version.  Note: All tools from a single build will " +
		"have the same semantic version number (0.0.0)."
	FlagWordsize     = "wordsize"
	FlagWordSizeText = "Specify the number of characters in a word generated by the Sequence or Random " +
		"source generators."
	/*
		miscellaneous parts.
	*/
	FlagPrefix    = "--"
	FlagShortHelp = "-h"
)
